@PORT=8000
@HOST=http://localhost
@POKEMON_NAME=BLASTOISE


### REST TEMPLATE

### REQUISICAO DIRETA EM RESPONSE ENTITY
GET {{HOST}}:{{PORT}}/rest-template/pokemon/{{POKEMON_NAME}} HTTP/1.1


### LENDO DADOS JSON
GET {{HOST}}:{{PORT}}/rest-template/pokemon/json/{{POKEMON_NAME}} HTTP/1.1


### LENDO DADOS MAPPED CLASS
GET {{HOST}}:{{PORT}}/rest-template/pokemon/class/{{POKEMON_NAME}} HTTP/1.1
